apiVersion: v1
kind: Service
metadata:
  name: {{ include "steam-roulette.name" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steam-roulette.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: {{ include "steam-roulette.name" . }}-frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}