{{- $backendSecret := .Values.backend.createSecret -}}
{{- $postgresSecret := and .Values.postgres.enabled .Values.postgres.createSecret -}}
{{- if $backendSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steam-roulette.labels" . | nindent 4 }}
type: Opaque
stringData:
  STEAM_API_KEY: {{ .Values.steamApiKey | quote }}
  METRICS_TOKEN: {{ .Values.metricsToken | quote }}
{{- end }}
{{- if and $backendSecret $postgresSecret }}
---
{{- end }}
{{- if $postgresSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steam-roulette.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:%v/%s" .Values.postgres.username .Values.postgres.password (include "steam-roulette.name" .) .Values.postgres.port .Values.postgres.database | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
