{{- if .Values.backend.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "steam-roulette.name" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steam-roulette.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: {{ include "steam-roulette.name" . }}-backend
  endpoints:
    - port: http
      path: {{ .Values.backend.metrics.path }}
      interval: 15s
      authorization:
        credentials:
          name: {{ .Values.backend.secretName }}
          key: METRICS_TOKEN
{{- end }}