image:
  registry: ghcr.io
  repository: nesic99/steam-roulette
  pullPolicy: Always

backend:
  image:
    tag: latest
  replicaCount: 1
  port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  secretName: steam-roulette-secret
  service:
    type: NodePort
    nodePort: 30503

frontend:
  image:
    tag: latest
  replicaCount: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: NodePort
    nodePort: 30082

ingress:
  enabled: false

namespace: steam-roulette